config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    # get '/users/log_in' => 'devise/sessions#new'
  end
  root 'pages#index'
  resources :rooms
  resources :bookings
  resources :reviews

  namespace :admin do
    resources :reviews do
      member do
        get :confirmation
      end
    end
    resources :bookings do
      member do
        get :confirmation
      end
    end
    resources :rooms, :bookings, :reviews
    get '/admin/dashboard', as: :authenticated_root
    get 'dashboard', to: 'pages#dashboard'
    get 'export(.:format)', to: 'bookings#export'
    post '/admin/rooms/new', to: 'rooms#create'
  end
  unauthenticated :users do
    namespace :admin do
      root to: 'session#new', as: :unauthenticated_root
    end
  end
end

app/models/room.rb
# frozen_string_literal: true

class Room < ApplicationRecord
  has_many :booking
  has_many_attached :room_photos, dependent: :destroy

  validates :title,
            presence: true,
            length: { minimum: 5, maximum: 100 }
  validates :description,
            presence: true,
            length: { minimum: 10, maximum: 5000 }

  def self.available_rooms(check_in, check_out)
    Booking.excluded_id(check_in, check_out)
  end
end

app/controllers/admin/rooms_controller.rb
# frozen_string_literal: true

module Admin
  class RoomsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_room, except: %i[index new create]
    def index
      @rooms = Room.all.order(created_at: :desc)
    end

    def show; end

    def new
      @room = Room.new
    end

    def edit; end

    def create
      @room = Room.new(room_params)
      add_room_photos
      respond_to do |f|
        if @room.save
          f.html { redirect_to admin_rooms_url(@room), notice: 'Room was created.' }
        else
          f.html { render :new, status: :bad_request }
        end
      end
    end

    def update
      add_room_photos
      respond_to do |f|
        if @room.update(room_params)
          f.html { redirect_to admin_rooms_url(@room), notice: 'Room was updated.' }
        else
          f.html { render :edit, status: :bad_request }
        end
      end
    end

    def destroy
      @room.destroy
      respond_to do |f|
        f.html { redirect_to admin_rooms_url, notice: 'Room was destroyed.' }
      end
    end

    private

    def set_room
      @room = Room.find(params[:id])
    end

    def room_params
      params.require(:room).permit(:title, :description, :price, room_photos: [])
    end

    def add_room_photos
      @room.room_photos.attach(params[:room_photos])
    end
  end
end

app/controllers/rooms_controller.rb
# frozen_string_literal: true

class RoomsController < ApplicationController
  before_action :set_room, only: %i[show]
  def index
    @rooms = Room.all.order(created_at: :desc)
  end

  def show
    @booking = Booking.new
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end
end

app/views/admin/rooms/_form.html.erb
<%= form_with(model: @room, url: admin_rooms_url, html: { multipart: true }) do |form| %>
  <% if @room.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>
      <ul>
        <% @room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="row">
    <div class="col-xs-10">
      <%= form_with(model: @room, method: :post, html: {class: "form-horizontal", role: "form"}) do |form| %>
        <div class="form-group">
          <div class="control-label col-sm-12">
            <%= form.label :title %>
          </div>
          <div class="col-sm-6">
            <%= form.text_field :title, class: "form-control", autofocus: true %>
          </div>
        </div>

        <div class="form-group">
          <div class="control-label col-sm-12">
            <%= form.label :description %>
          </div>
          <div class="col-sm-8">
            <%= form.text_area :description, rows: 10, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <div class="control-label col-sm-12">
            <%= form.label :price %>
          </div>
          <div class="col-sm-8">
            <%= form.text_field :price, rows: 10, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <div class="control-label col-sm-12">
            <%= form.label :room_photos %>
          </div>
          <div class="col-sm-8">
            <%= form.file_field :room_photos,  rows: 10, class: "form-control", multiple: true %>
          </div>
        </div>

        <div class="form-group">
          <div class="control-label col-sm-10">
            <%= form.submit class: 'btn btn-primary btn-large' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/admin/rooms/_room.html.erb
<div id="<%= dom_id room %>">
  <div class="row">
    <div class="col-xs-8">
      <strong>The room</strong>
    </div>
    <div class="col-xs-8">
      <div class="well well-lg">
        <div class="article-title">
          <strong>Title:</strong>
          <%= room.title %>
        </div>
        <div class="article-title">
          <strong>Description:</strong>
          <%= room.description %>
        </div>
        <div class="article-title">
          <strong>Price:</strong>
          <%= room.price %>
        </div>
        <div class="article-body">
          <hr />
          <% room.room_photos.each do |photo| %>
            <%= link_to image_tag(photo, style:"width:200px; height:200px"), photo %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Show this room", admin_room_path %> |
  <%= link_to "Back to other rooms", admin_rooms_path %>
</div>

app/views/admin/rooms/index.html.erb
<h1>Table of rooms</h1>

<%= link_to "Add new room", new_admin_room_path %>
<style>
    table, th, td {
        border: 2px solid white;
    }

    th, td {
        background-color: #DCDCDC;
    }
</style>
<table class="table">
  <tr>
    <th scope="col">Room title</th>
    <th scope="col">Created at</th>
    <th scope="col">Updated at</th>
    <th scope="col">Open</th>
    <th scope="col">Update</th>
    <th scope="col">Destroy</th>
  </tr>
  <% @rooms.each do |admin_room| %>
    <tr>
      <td><%= admin_room.title %></td>
      <td><%= admin_room.created_at %></td>
      <td><%= admin_room.updated_at %></td>
      <td><%= button_to "Open", admin_room_path(admin_room), method: :get, class: "btn btn-xs btn-primary" %></td>
      <td><%= button_to "Update", edit_admin_room_path(admin_room), method: :get, class: "btn btn-xs btn-warning" %></td>
      <td><%= button_to "Destroy", admin_room_path(admin_room), method: :delete, class: "btn btn-xs btn-danger" %></td>
    </tr>
  <% end %>
</table>

app/views/admin/rooms/new.html.erb
<h1>New room</h1>
<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Back to other rooms", admin_rooms_path %>
</div>

app/views/admin/rooms/show.html.erb
<%= render @room %>
<hr/>
<div>
  <%= link_to "Back to other rooms", admin_rooms_path %>
</div>
<hr/>
<div>
  <%= button_to "Destroy this room", admin_room_path(@room), method: :delete %>
</div>