config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    # get '/users/log_in' => 'devise/sessions#new'
  end
  root 'pages#index'
  resources :rooms
  resources :bookings
  resources :reviews

  namespace :admin do
    resources :reviews do
      member do
        get :confirmation
      end
    end
    resources :bookings do
      member do
        get :confirmation
      end
    end
    resources :rooms, :bookings, :reviews
    get '/admin/dashboard', as: :authenticated_root
    get 'dashboard', to: 'pages#dashboard'
    get 'export(.:format)', to: 'bookings#export'
    post '/admin/rooms/new', to: 'rooms#create'
  end
  unauthenticated :users do
    namespace :admin do
      root to: 'session#new', as: :unauthenticated_root
    end
  end
end

app/controllers/admin/reviews_controller.rb
# frozen_string_literal: true

module Admin
  class ReviewsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_review, only: %i[show update destroy confirmation]
    attr_reader :review

    def index
      @reviews = Review.all.order(created_at: :desc)
    end

    def show; end

    def update
      respond_to do |f|
        if @review.update(review_params)
          f.html { redirect_to admin_review_url(@review), notice: 'Review was updated.' }
        else
          f.html { render :edit, status: :bad_request }
        end
      end
    end

    def destroy
      @review.destroy
      respond_to do |f|
        f.html { redirect_to admin_reviews_url, notice: 'Review was destroyed.' }
      end
    end

    def confirmation
      if @review.pended?
        @review.published!
      elsif @review.published?
        @review.pended!
      end

      redirect_to admin_reviews_url, notice: 'Review status was updated.'
    end

    private

    def set_review
      @review = Review.find(params[:id])
    end

    def review_params
      params.require(:review).permit(:username, :email, :description)
    end
  end
end

app/controllers/reviews_controller.rb
# frozen_string_literal: true

class ReviewsController < ApplicationController
  before_action :set_review, only: %i[show]
  def index
    @reviews = Review.all.published.order(created_at: :desc)
    @review = Review.new
  end

  def show; end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)

    respond_to do |f|
      if @review.save
        f.html { redirect_to review_url(@review), notice: 'Review was created.' }
      else
        f.html { render :new }
      end
    end
  end

  private

  def review_params
    params.require(:review).permit(:username, :email, :description)
  end

  def set_review
    @review = Review.find(params[:id])
  end
end

app/views/admin/reviews/_review.html.erb
<div class="well well-lg">
  <% unless review.published %>
    <div id="<%= dom_id review %>">
      <p>
        <strong>Name:</strong>
        <%= review.username %>
      </p>

      <p>
        <strong>Email:</strong>
        <%= review.email %>
      </p>

      <p>
        <strong>Review:</strong>
        <%= review.description %>
      </p>

      <p>
        <br/>
        <%= button_to "Publish this review", admin_review_path(review), method: :put, class: 'btn btn-warning' %>
        <br/>
        <%= button_to "Destroy this review", admin_review_path(review), method: :delete, class: 'btn btn-danger' %>
      </p>
    </div>
  <% end %>
</div>

app/views/admin/reviews/index.html.erb
<h1>Table of reviews</h1>
<style>
    table, th, td {
        border: 2px solid white;
    }

    th, td {
        background-color: #DCDCDC;
    }
</style>
<table class="table">
  <tr>
    <th scope="col">Username</th>
    <th scope="col">Email</th>
    <th scope="col">Description</th>
    <th scope="col">Status</th>
    <th scope="col">Created at</th>
    <th scope="col">Updated at</th>
    <th scope="col">Status</th>
    <th scope="col">Destroy</th>
  </tr>
  <% @reviews.each do |admin_review| %>
    <tr>
      <td><%= admin_review.username %></td>
      <td><%= admin_review.email %></td>
      <td><%= admin_review.description %></td>
      <td><%= admin_review.status %></td>
      <td><%= admin_review.created_at %></td>
      <td><%= admin_review.updated_at %></td>
      <td><%= button_to "Confirm", confirmation_admin_review_path(admin_review), method: :get, class: "btn btn-xs btn-warning" %></td>
      <td><%= button_to "Destroy", admin_review_path(admin_review), method: :delete, class: "btn btn-xs btn-danger" %></td>
    </tr>
  <% end %>
</table>

app/views/admin/reviews/show.html.erb
<% render @review %>