config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    # get '/users/log_in' => 'devise/sessions#new'
  end
  root 'pages#index'
  resources :rooms
  resources :bookings
  resources :reviews

  namespace :admin do
    resources :reviews do
      member do
        get :confirmation
      end
    end
    resources :bookings do
      member do
        get :confirmation
      end
    end
    resources :rooms, :bookings, :reviews
    get '/admin/dashboard', as: :authenticated_root
    get 'dashboard', to: 'pages#dashboard'
    get 'export(.:format)', to: 'bookings#export'
    post '/admin/rooms/new', to: 'rooms#create'
  end
  unauthenticated :users do
    namespace :admin do
      root to: 'session#new', as: :unauthenticated_root
    end
  end
end

app/models/booking.rb
# frozen_string_literal: true

class Booking < ApplicationRecord
  belongs_to :room
  enum status: { pended: 0, confirmed: 1 }

  validates :check_in,
            presence: true
  validates :check_out,
            presence: true
  validates :people,
            presence: true
  validates :room_id,
            presence: true

  after_update :enqueue

  def rooms_are_available
    @booked_rooms = Room.available_rooms(check_in, check_out)
    errors.add('This room is not available for these dates.') if @booked_rooms.include?(room_id)
  end

  def enqueue
    ExportBookingsJob.perform_later if status == 1
  end

  def self.to_csv
    CSV.generate(col_step: ';') do |csv|
      csv << attribute_names
      confirmed_bookings.find_each do |record|
        csv << record.attributes.values
      end
    end
  end

  def self.to_xlsx
    workbook = RubyXL::Workbook.new
    worksheet = workbook.add_worksheet('Confirmed bookings')
    worksheet.add_cell(0, 0, 'Status')
    worksheet.add_cell(0, 1, 'Username')
    worksheet.add_cell(0, 2, 'Email')
    worksheet.add_cell(0, 3, 'Check_in')
    worksheet.add_cell(0, 4, 'Check_out')
    worksheet.add_cell(0, 5, 'People')
    worksheet.add_cell(0, 6, 'Room_id')
    worksheet.add_cell(0, 7, 'Created_at')
    worksheet.add_cell(0, 8, 'Updated_at')
    counter = 1
    Booking.confirmed_bookings.each do |book|
      worksheet.add_cell(counter, 0, book.status)
      worksheet.add_cell(counter, 1, book.username)
      worksheet.add_cell(counter, 2, book.email)
      worksheet.add_cell(counter, 3, book.check_in)
      worksheet.add_cell(counter, 4, book.check_out)
      worksheet.add_cell(counter, 5, book.people)
      worksheet.add_cell(counter, 6, book.room_id)
      worksheet.add_cell(counter, 7, book.created_at)
      worksheet.add_cell(counter, 8, book.updated_at)
      counter += 1
    end
    workbook.write('confirmed_bookings.xlsx')
  end

  scope :confirmed_bookings, -> { Booking.where(status: 1) }
end

app/controllers/admin/bookings_controller.rb
# frozen_string_literal: true

module Admin
  class BookingsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_booking, only: %i[show edit update destroy confirmation]
    def index
      @bookings = Booking.all.order(created_at: :desc)
    end

    def show
      @room = @booking.room
    end

    def update
      respond_to do |f|
        if @booking.update(booking_params)
          f.html { redirect_to admin_booking_url(@booking), notice: 'Booking was updated.' }
        else
          f.html { render :new, status: :bad_request }
        end
      end
    end

    def destroy
      @booking.destroy
      respond_to do |f|
        f.html { redirect_to admin_bookings_url, notice: 'Booking was destroyed.' }
      end
    end

    def confirmation
      if @booking.pended?
        @booking.confirmed!
      elsif @booking.confirmed?
        @booking.pended!
      end
      respond_to do |f|
        f.html { redirect_to admin_bookings_url, notice: 'Booking status was updated.' }
      end
    end

    def export
      @bookings = Booking.confirmed_bookings
      respond_to do |f|
        f.csv do
          response.headers['Content-Type'] = 'text/csv'
          response.headers['Content-Disposition'] = 'attachment;filename=confirmed_bookings.csv'
          render template: 'admin/bookings/index'
        end

        f.xlsx do
          response.headers['Content-Type'] = 'text/xlsx'
          response.headers['Content-Disposition'] = 'attachment;filename=confirmed_bookings.xlsx'
          render xlsx: 'bookings', template: 'admin/bookings/index'
        end
      end
    end

    private

    def set_booking
      @booking = Booking.find(params[:id])
    end

    def booking_params
      params.require(:booking).permit(:username, :email, :check_in, :check_out, :people, :room_id)
    end
  end
end

app/controllers/bookings_controller.rb
# frozen_string_literal: true

class BookingsController < ApplicationController
  before_action :set_booking, only: %i[show edit update destroy confirmation]
  def index
    @bookings = Booking.all.order(created_at: :desc)
  end

  def show
    @room = @booking.room
  end

  def new
    @booking = Booking.new
  end

  def update
    respond_to do |f|
      if @booking.update(booking_params)
        f.html { redirect_to booking_url(@booking), notice: 'Booking was updated.' }
      else
        f.html { render :edit, status: :bad_request }
      end
    end
  end

  def create
    @booking = Booking.new(booking_params)
    respond_to do |f|
      if @booking.save
        f.html { redirect_to booking_url(@booking), notice: 'Booking was created.' }
      else
        f.html { render :new, status: :bad_request }
      end
    end
  end

  def destroy
    @booking.destroy
    respond_to do |f|
      f.html { redirect_to bookings_url, notice: 'Booking was destroyed.' }
    end
  end

  def edit; end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:username, :email, :check_in, :check_out, :people, :room_id)
  end
end

app/views/bookings/_booking.html.erb
<div id="<%= dom_id booking %>">
  <p>
    <strong>Name:</strong>
    <%= booking.username %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= booking.email %>
  </p>

  <p>
    <strong>Check in date::</strong>
    <%= booking.check_in %>
  </p>

  <p>
    <strong>Check out date:</strong>
    <%= booking.check_out %>
  </p>

  <p>
    <strong>Number of people:</strong>
    <%= booking.people %>
  </p>

  <p>
    <strong>Room:</strong>
    <%= booking.room_id %>
  </p>

  <hr />
  <% booking.room.room_photos.each do |photo| %>
    <%= link_to image_tag(photo, style:"width:200px; height:200px"), photo %>
  <% end %>
</div>

app/views/bookings/_form.html.erb
<%= form_with(model: @booking) do |form| %>
  <% if @booking.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
        <% @booking.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :check_in, style: "display: block" %>
    <%= form.date_field :check_in %>
  </div>

  <div>
    <%= form.label :check_out, style: "display: block" %>
    <%= form.date_field :check_out %>
  </div>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :people, style: "display: block" %>
    <%= form.number_field :people %>
  </div>

  <div>
    <%= form.label :room_id, style: "display: block" %>
    <%= form.number_field :room_id, :value => room_id %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing booking</h1>

<%= render "form", booking: @booking, room_id: @booking.room_id %>

<br>

<div>
  <%= link_to "Open booking", @booking %> |
  <%= link_to "Back to other bookings", bookings_path %>
</div>

app/views/bookings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Bookings</h1>
<div id="bookings">
  <% @bookings.each do |booking| %>
    <%= render booking %>
    <p>
      <%= link_to "Open this booking", booking %>
    </p>
  <% end %>
</div>

<%= link_to "New booking", new_booking_path %>

app/views/bookings/new.html.erb
<h1>New booking</h1>

<%= render "form", booking: @booking %>

<br>

<div>
  <%= link_to "Back to other rooms", rooms_path %>
</div>

app/views/bookings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @booking %>

<div>
  <%= link_to "Edit this booking", edit_booking_path(@booking) %> |
  <%= button_to "Destroy this booking", @booking, method: :delete %>
</div>