config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    # get '/users/log_in' => 'devise/sessions#new'
  end
  root 'pages#index'
  resources :rooms
  resources :bookings
  resources :reviews

  namespace :admin do
    resources :reviews do
      member do
        get :confirmation
      end
    end
    resources :bookings do
      member do
        get :confirmation
      end
    end
    resources :rooms, :bookings, :reviews
    get '/admin/dashboard', as: :authenticated_root
    get 'dashboard', to: 'pages#dashboard'
    get 'export(.:format)', to: 'bookings#export'
    post '/admin/rooms/new', to: 'rooms#create'
  end
  unauthenticated :users do
    namespace :admin do
      root to: 'session#new', as: :unauthenticated_root
    end
  end
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Hotel Noveo", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li>
            <%= link_to "Check reviews", admin_reviews_path, class: 'nav-link' %>
          </li>
          <li>
            <%= link_to "Table of rooms", admin_rooms_path, class: 'nav-link' %>
          </li>
          <li>
            <%= link_to "List of bookings", admin_bookings_path, class: 'nav-link' %>
          </li>
        <% else %>
          <li>
            <%= link_to "Reviews", reviews_path, class: 'nav-link' %>
          </li>
          <li>
            <%= link_to "Rooms", rooms_path, class: 'nav-link' %>
          </li>
          <li>
            <!-- <%= link_to "Book", bookings_path, class: 'nav-link' %> -->
          </li>
        <% end %>
      </ul>
      <ul class="nav navbar-right navbar-nav">
        <% if user_signed_in? %>
          <li>
          <%= link_to "Log out", destroy_user_session_path, 'data-turbo-method': :delete, class: 'nav-link' %>
          </li>
        <% else %>
          <li>
            <%= link_to "Sign up", new_user_registration_path, class: 'nav-link' %>
          </li>
          <li>
            <%= link_to "Log in", new_user_session_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<section>
  <div id="intro" style="background-image: url('https://img.freepik.com/free-vector/white-abstract-background_23-2148810113.jpg?w=1380&t=st=1665413616~exp=1665414216~hmac=60133bf15e09b8e15e48e36a71acc2af9b3882ee0e1aa7202304c936e74b927c'); height: 10hv;">
    <div class="mask" style="background-color: #999999;"></div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hotel</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>